-- Consolidated schema for local introspection.
-- Generated by concatenating migrations; keep in sync manually.

\i migrations/000_init.sql
\i migrations/001_rls.sql
\i migrations/002_kpi.sql
\i migrations/003_members_email.sql
\i migrations/004_metrics_schema.sql
\i migrations/005_meta_table_renames.sql
\i migrations/006_meta_campaigns.sql
\i migrations/007_meta_insights_daily_expand.sql
\i migrations/008_meta_backfill_jobs.sql

